// <auto-generated />
using LindaWallace.Assets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LindaWallace.Assets.Data.Migrations
{
    [DbContext(typeof(AssetsContext))]
    partial class AssetsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LindaWallace.Assets.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetTypeId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Manufacturer")
                        .IsRequired();

                    b.Property<string>("Model");

                    b.Property<string>("SerialNumber")
                        .IsRequired();

                    b.Property<string>("TagNumber")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Assets");

                    b.HasData(
                        new { Id = 1, AssetTypeId = 1, Description = "Joe's Home Computer", Manufacturer = "Dell", Model = "Gold Plated", SerialNumber = "8765487", TagNumber = "456" },
                        new { Id = 2, AssetTypeId = 3, Description = "Catalog type description can be typed here", Manufacturer = "Dell", Model = "Basic", SerialNumber = "8765487", TagNumber = "628" },
                        new { Id = 3, AssetTypeId = 2, Description = "Best Monitor", Manufacturer = "HP", SerialNumber = "8765487", TagNumber = "248" },
                        new { Id = 4, AssetTypeId = 1, Description = "Joe's Work Computer", Manufacturer = "Acer", SerialNumber = "8765487", TagNumber = "963" }
                    );
                });

            modelBuilder.Entity("LindaWallace.Assets.Domain.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("AssetTypes");

                    b.HasData(
                        new { Id = 1, Name = "desktopComputer" },
                        new { Id = 2, Name = "computerMonitor" },
                        new { Id = 3, Name = "phone" }
                    );
                });

            modelBuilder.Entity("LindaWallace.Assets.Domain.Asset", b =>
                {
                    b.HasOne("LindaWallace.Assets.Domain.AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
